CREATE TABLE posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(60),
  description VARCHAR(60),
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

INSERT INTO posts(title, description)
VALUES 
  ('Post #1', 'first post'),
  ('Post #2', 'second post');

CREATE TABLE events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fixture_id INT,
  home_team_id INT,
  home_team_name VARCHAR(60),
  home_team_image VARCHAR(120),
  home_team_score INT,
  visitor_team_id INT,
  visitor_team_name VARCHAR(60),
  visitor_team_image VARCHAR(120),
  visitor_team_score INT,
  venue VARCHAR(60),
  city VARCHAR(60),
  country VARCHAR(60),
  date timestamp,
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

INSERT INTO events(fixture_id, home_team_name, home_team_id, home_team_score, visitor_team_name, 
visitor_team_id, visitor_team_score)
VALUES 
  (1, 'Neuchâtel Xamax FCS', 1, 3, 'Lausanne Sport', 2, 0),
  (2, 'FC Basel', 3, 2, 'FC Zürich', 4, 2);

-- 2. Enable RLS (Prevent any action on the table)
ALTER TABLE events 
  enable row level security;

CREATE UNIQUE INDEX fixture_idx ON events (fixture_id);

CREATE TABLE messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id INT,
  user_id INT,
  user_email VARCHAR(255),
  content VARCHAR(255),
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);